kafka:
  bootstrapAddress: localhost:9092
  consumer:
    groupId: order-prosessor
  producer:
    clientId: payment-initiator
  stores:
    paymentOrder: payment-order-joinOn-orderId
  topic:
    payment: payment
    order: order
server:
  port: 8081
